name: Deploy Complex
on:
  push:
    branches:
      - master

env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$KUBERNETES_PHRASE" --output service-account.json service-account.json.gpg
        env:
          KUBERNETES_PHRASE: ${{ secrets.KUBERNETES_PHRASE }}
      - run: echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run: sudo apt-get clean
      - run: curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-390.0.0-linux-x86_64.tar.gz -o google-cloud-cli-390.0.0-linux-x86.tar.gz
      - run: tar -zxf google-cloud-cli-390.0.0-linux-x86.tar.gz
      - run: ./google-cloud-sdk/install.sh
      - run: source ~/.bashrc
      - run: sudo apt-get update && sudo apt-get --only-upgrade install kubectl google-cloud-sdk-kubectl-oidc
      - run: gcloud auth activate-service-account --key-file service-account.json
      - run: gcloud config set project multi-k8s-354008
      - run: gcloud config set compute/zone europe-west3-a
      - run: gcloud container clusters get-credentials multi-cluster
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t simonpcpc/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true simonpcpc/react-test npm test
      
      - name: set sha variable
        id: sha-var
        run: |
          echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Deploy to GKE
        run: bash ./deploy.sh