name: Deploy Complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(pwd)
      - run: echo $HOME
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$KUBERNETES_PHRASE" --output service-account.json service-account.json.gpg
      - run: curl https://sdk.cloud.google.com | bash > /dev/null;
      - run: source $HOME/google-cloud-sdk/path.bash.inc
      - run: gcloud components update kubectl
      - run: gcloud auth activate-service-account --key-file service-account.json